### PR TITLE
fix OR node choice variables

### LINKED ISSUE #9: Question about unlabeled OR nodes
I'm intrigued as to why only some OR nodes are labeled with an opposing variable.
The corresponding code is here
https://github.com/QuMuLab/dsharp/blob/b8b25260632df82ed9b202e66fd156a68299207c/src/src_sharpSAT/MainSolver/DecisionTree.cpp#L726-L731
and does not explain why only positive literals are valid opposing variables.
I tried to patch this away, 
```diff
diff --git a/src/src_sharpSAT/MainSolver/DecisionTree.cpp b/src/src_sharpSAT/MainSolver/DecisionTree.cpp
index a9a3f11..6311652 100644
--- a/src/src_sharpSAT/MainSolver/DecisionTree.cpp
+++ b/src/src_sharpSAT/MainSolver/DecisionTree.cpp
@@ -724,8 +724,8 @@ void DTNode::genNNF(ostream & out)
 	else if (DT_OR == type)
 	{
 		//Dimitar Sht. Shterionov: ignoring negative values on OR nodes
-		if (choiceVar > 0)
-			out << "O " << choiceVar << " " << children.size();
+		if (true)
+			out << "O " << std::abs(choiceVar) << " " << children.size();
 		else
 			out << "O 0 " << children.size();
 
diff --git a/src/src_sharpSAT/MainSolver/MainSolver.h b/src/src_sharpSAT/MainSolver/MainSolver.h
index 1eb440c..1ef75cd 100644
--- a/src/src_sharpSAT/MainSolver/MainSolver.h
+++ b/src/src_sharpSAT/MainSolver/MainSolver.h
@@ -333,7 +333,7 @@ public:
 					out << "AND";
 					break;
 				case DT_OR:
-					out << "OR";
+					out << "OR " << node->choiceVar;
 					break;
 				case DT_BOTTOM:
 					out << "F";
```
but of course this leads to incorrect results:
with 
```cnf
p cnf 4 16
-2 1 4 0
3 1 -4 0
-2 3 -4 0
1 4 3 0
3 -1 -2 0
1 -4 3 0
4 2 3 0
-1 -2 4 0
2 -1 3 0
3 -4 1 0
2 -1 4 0
-4 1 -2 0
3 -4 -2 0
2 3 -4 0
3 2 -4 0
2 -1 -4 0
```
and priority to variables 2,4 I get
```
nnf 13 16 4
L -2
L -1
L -4
L 3
A 4 0 1 2 3
L 4
A 2 0 1
L 2
L 1
A 2 7 8
O 0 2 6 9
A 3 5 3 10
O 0 2 4 11
```
with vanilla dsharp (see the two unlabeled OR nodes)
and with the patched dsharp I get
```
nnf 13 16 4
L -2
L -1
L -4
L 3
A 4 0 1 2 3
L 4
A 2 0 1
L 2
L 1
A 2 7 8
O 1 2 6 9
A 3 5 3 10
O 3 2 4 11
```
but the label 3 on the last OR node is incorrect: both branches lead to node 3 (L 3).
graph

### PR DESCRIPTION
**Pull request by symphorien**
* choice variables are variables (unsigned) not literals (signed)
* remove conditional in NNF code that becomes redundant based on the
above
* fix that literals are translated but not choice variables, which could lead to
wrong OR node labeling

fixes #9

### CODE REVIEW

**Comment by haz** [comment]
Pity we need to resort to the more complex recursive approach, but don't really see any way around it...

There any risk of the `choiceVar` being `unsigned` when the keys to the translation are `int`?

**Comment by symphorien** [comment]
> There any risk of the choiceVar being unsigned when the keys to the translation are int?

All assignments to choiceVar are visible in the diff, and all of correct type unless I'm mistaken.

File: src/src_sharpSAT/MainSolver/MainSolver.h [hunk 1]
```diff
@@ -442,14 +442,54 @@ class CMainSolver: public CInstanceGraph
...
+					else
+					{
+						node->setVal(varTranslation[node->getVal()]);
+					}
+				}
+
+				if (DT_OR == node->getType())
+				{
+					if (node->choiceVar) {
+						node->choiceVar = varTranslation[node->choiceVar];
```
Comment (haz) [inline src/src_sharpSAT/MainSolver/MainSolver.h:488]: It's this line I'm concerned with. `varTranslation` comes in as `vector<int>`, and while the other instances are `int`, this one comes in as `unsigned`.

Comment (symphorien) [reply src/src_sharpSAT/MainSolver/MainSolver.h:488]: Oh indeed ! I had missed this one !
I went all the way and fixed the translation vector to contain unsigned values. i'm fairly confident that it's correct because I can compile sucessfully with `-Wsign-promo -Wsign-conversion -Wsign-compare -Werror `

**Comment by haz** [comment]
Looks much better now, thanks!

I've never introspected what was being stored on the decision nodes. You happy with half of em coming back with `0` as an entry?

out-br

That's what's generated with this CNF:

```
p cnf 4 3
2 0
1 3 0
-1 4 0
```

**Comment by symphorien** [comment]
Unfortunately, no, I really need all OR nodes to be indexed with a decision variable.

**Comment by haz** [comment]
Hrmz...then I think the node merging done during simplification needs to be modified to retain the correct decision node (parent rather than child). Is it fine for having only one reason for determinism? E.g., `Or(And(1, 2), And(-1, -2))` could come from branching on either 1 or 2.

**Comment by symphorien** [comment]
One reason is fine by me if it respect priority variables: if 1 is priority and 2 is not, 1 should be retained.

**Comment by haz** [comment]
Looks like it's not the merger, but the other places where `Or` nodes are created (I've identified 5 spots). Will give it a go over lunch (hour or two).

**Comment by haz** [comment]
@symphorien Can you give me push access to your fork? I have a set of changes to push.

Btw, this is what we should be able to generate now (same example as above):
out

**Comment by symphorien** [comment]
I think I have already ticked the box
image

**Comment by haz** [comment]
Might need to add me as a maintainer on the repo. This is what I'm getting:

```bash
$ git push symphorien HEAD:opposing
remote: Permission to symphorien/dsharp.git denied to haz.
fatal: unable to access 'https://github.com/symphorien/dsharp/': The requested URL returned error: 403
```

**Comment by symphorien** [comment]
I invited you, then :)

**Comment by haz** [comment]
Thanks! That seemed to do the trick. How's e76dbc1 look?

**Comment by symphorien** [comment]
It passes my tests, and the diff looks good :)
